# Generated by Django 5.1.4 on 2024-12-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Found_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_item_name', models.CharField(max_length=100)),
                ('found_item_description', models.TextField()),
                ('found_item_img', models.ImageField(upload_to='images/found/')),
            ],
        ),
        migrations.CreateModel(
            name='Lost_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_item_name', models.CharField(max_length=100)),
                ('lost_item_description', models.TextField()),
                ('lost_item_img', models.ImageField(upload_to='images/lost/')),
            ],
        ),
    ]
