# Generated by Django 5.1.4 on 2024-12-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='found_item',
            name='founder_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lost_item',
            name='owner_contact',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
